### ISSUE TITLE
Quizz

### ISSUE THREAD

**Issue by JVRasa** [ComicScrip/lyon-react-mars22-p2g2#15]
# Le besoin

En tant qu'utilisateur, je souhaite qu'on me propose des films suite à un quiz afin de ne pas avoir à toucher aux filtres

## Critères et considérations spécifiques

- [x] Conformité à l'écran "quizz" sur la maquette
- [x] Deux boutons réponses 
- [x] Quiz de 5 questions

#### Actions à réaliser

- se rendre sur la page "quiz" accessible depuis l'URL `/quizz` ou depuis la page d'accueil
- lire les questions du quiz et répondre via un bouton "réponse A" ou "réponse B"

#### Verifications

- [x] On voit bien le quizz
- [x] On peut cliquer sur les réponses et passer à la suivante
- [x] On a 5 questions

## A faire

- [x] Imaginer 5 questions associées à des valeurs de filtre
- [x] Composant QuizzQuestion qui contient la question et les deux réponses
- [x] Faire passer à la question suivante et sauvegarder la valeur du filtre associée à la réponse quand on click sur une réponse

**Comment by ComicScrip** [comment]
Issue modifiée et validée
