### ISSUE TITLE
Filtre - Pays d'origine du film / année de sortie / note

### ISSUE THREAD

**Issue by RayaneArroudj** [ComicScrip/lyon-react-mars22-p2g2#16]
# Le besoin

En tant qu'utilisateur, je souhaite pouvoir utiliser un filtre concernant le pays d'origine du film et/ou l'année de sortie et/ou la note , afin de  pouvoir filtrer ma sélection par pays / année / note.

## Critères et considérations spécifiques

- [x] Sélectionner les filtres
- [x] Filtrage par pays
- [x] Filtrage par période d'année de sortie
- [x] Filtrage par note

#### Actions à réaliser

- Se rendre sur la page "Filtre" accessible depuis l'URL `/movies`
- Choisir les filtres différents en essayant plusieurs combinaisons

#### Verifications

- [x] On voit bien les filtres à l'écran
- [x] Une liste de pays apparaît
- [x] Une liste d'années apparaît
- [x] Une liste de notes apparaît
- [x] L'utilisateur peut choisir un pays / année / note présent dans la liste
- [x] Les films correspondent bien au pays / année / note sélectionnés via les filtres

## A faire

- [x] Créer les filtres
- [x] Créer une liste de pays : Brésil, Mexique, US, Chine, HongKong, Thailande, Japon, Inde, France, Espagne, Russie, Turquie, Afrique du sud
- [x] Créer une liste d'années : Avant 1960, Entre 1961 et 1980, Entre 1981 et 2000, Entre 2001 et 2010, Entre 2011 et aujourd'hui
- [x] Créer une liste de notes : Moins de 1 étoile, De 1 à 2 étoiles, De 2 à 3 étoiles
- [x] Adapter les appels à L'API afin de filtrer sur le pays / année / note choisie
- [x] Cacher les filtres non utilisables pour le moment

**Comment by ComicScrip** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/16140010/165293664-c98e98a3-9766-4eaa-9512-8d153d5e6332.png">

Peut-on modifier la maquette mobile pour avoir les filtres les uns en dessous des autres ? J'ai peur que ça ne soit pas super visible sinon

**Comment by ComicScrip** [comment]
Issue modifiée et validée
