### ISSUE TITLE
Detail Page

### ISSUE THREAD

**Issue by QuintinJouanne** [ComicScrip/lyon-react-mars22-p2g2#30]
# Le besoin
En tant qu'utilisateur , je souhaite acceder au détail du film , afin d'obtenir davantage de renseignement.

## Critères et considérations spécifiques
- [x] Conformité à la maquette (MobileFirst + Desktop).

#### Actions à réaliser
- [x]  Se rendre sur la page "detailpage" accessible depuis l'URL `/movies/:id`.
- [x]  Le trailer change de place en fonction de la taille de l'écran.

#### Verifications
- [x]  Présence des différents elements (image du film, titre, date de sortie, realisateur, runtime, synopsis, nom des acteurs et leurs photos).
- [x]  Possibilité de visualiser le trailer.
- [x]  Le trailer change bien de place en fonction de la resolution écran.
- [x] Le câblage à L'API est fonctionnel : on peut accéder à n'importe quel film avec un identifiant valide sur l'API

## A faire
- [x] Squelette de la page.
- [x] Mise en place de l'API
- [x] SetIsLoading à mettre en place pour indiquer le chargement de l'API
- [x] Lorsqu'il n'y a pas de trailer, mettre en place une fonction permettant à l'utilisateur d'en être informé.

## (A ne pas faire)
- L'utilisateur ne doit pas pouvoir cliquer sur le elements de la page hormis le trailer.

**Comment by ComicScrip** [comment]
"Mise en place de l'API" dans les actions à réaliser par l'utilisateur. Je ne crois pas...
J'ai modifié l'issue

**Comment by ComicScrip** [comment]
Je vous laisse remplacer `/movies/:id` par quelque chose avec un identifiant valide dans l'issue
