### ISSUE TITLE
Nanar mate

### ISSUE THREAD

**Issue by JVRasa** [ComicScrip/lyon-react-mars22-p2g2#42]
# Le besoin

En tant qu'utilisateur , je souhaite pouvoir rencontrer d'autre membres de la communauté dans l'optique d'aller voir un film ensemble.

## Critères et considérations spécifiques

- [ ] Conformité à l'écran "Nanar Mate" sur la maquette

#### Actions à réaliser

- se rendre sur la page "Nanar Mate" accessible depuis l'URL `/nanarmates`

#### Verifications

- [x] On voit les dispos des membres de la communauté
- [x] Seules les dispo futures sont affichées
- [x] Les dispo sont triées de la plus proche à la plus lointaine dans le temps

#### Actions à réaliser

- se rendre sur la page "Nanar Mate" accessible depuis l'URL `/nanarmates`
- remplir le formulaire avec les champs "nom", "date", "localisation", "film" et l'envoyer

#### Verifications

- [x] On voit bien le formulaire, on peut sélectionner n'importe quel film venant de l'API avec une liste déroulante
- [x] Messages d'erreur lorsque les champs ne sont pas tous remplis
- [x] Avoir un visuel de confirmation d'envoi (succès) ou d'échec (fail) lorsque je post mon message.
- [x] Les champs "film" et "heure" sont réinitialisés après l'envoie, de manière à ce que je puisse ajouter un autre film rapidement sur un crénau différent
- [x] Je peux retrouver ma dispo dans la liste

## A faire

- [x] Définir quelques points de RDV (4-5) dans Lyon et noter les coordonées GPS
- [x] Créer une database avec une table "availabilities" ("userName" "location" "date", "hour", "movieName") ainsi que quelques examples de dispo dans un `resetDB.sql`
- [x] Créer une routes GET `/availabilities` avec un filtre `min_date`
- [x] Créer une routes POST `/availabilities` qui ajoute une entrée dans la table availabilities
- [x] Créer le formulaire en front
- [x] Appeler l'API tierce pour rendre la liste de tous les films dans un select (https://react-select.com/home) recherchable
- [x] Afficher un message d'erreur si les champs ne sont pas bien remplis
- [x] Cabler le formulaire à l'API homemade
- [x] Afficher une validation d'envoi du formulaire  (https://github.com/fkhadra/react-toastify)

**Comment by ComicScrip** [comment]
Issue modifiée, j'ai inclus la lecture car sinon la fonctionnalité d'ajout n'est pas vraiment utile.
