### ISSUE TITLE
Navigation et footer

### ISSUE THREAD

**Issue by JVRasa** [ComicScrip/lyon-react-mars22-p2g2#8]
# Le besoin

En tant qu'utilisateur , je souhaite naviguer sur le site , afin d'accéder aux différentes pages et fonctionnalités.

## Critères et considérations spécifiques

- [ ] Navbar et footer conformes aux maquettes
- [x] Liens vers les pages
- [ ] Dimensionner le header et footer pour tous les écrans
#### Actions à réaliser

- se rendre sur la page "Home" grâce au lien correspondant
- se rendre sur la page "Nanar localisation" grâce au lien correspondant
- se rendre sur la page "Quizz" grâce au lien correspondant
- se rendre sur la page "Contact" grâce au lien correspondant

#### Verifications

- [ ] La navbar & footer ressemblent à la maquette
- [x] On arrive à se déplacer sur les pages grâce aux liens
- [x] Le logo est présent

## A faire

- [x] Mettre le logo
- [ ] Liens vers les pages "Home" "Nanar localisation" "Quizz" "Contact"

## (A ne pas faire)

-

**Comment by ComicScrip** [comment]
duplicate of https://github.com/ComicScrip/lyon-react-mars22-p2g2/issues/44
